#nanodet-m-416
# COCO mAP(0.5:0.95) = 0.235
#             AP_50  = 0.384
#             AP_75  = 0.242
#           AP_small = 0.082
#               AP_m = 0.240
#               AP_l = 0.375
save_dir: workspace/rmcv_m
model:
  arch:
    name: OneStageDetector
    backbone:
      name: ShuffleNetV2
      model_size: 1.0x
      out_stages: [2,3,4]
      activation: LeakyReLU
    fpn:
      name: PAN
      in_channels: [116, 232, 464]
      out_channels: 96
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 18
      input_channel: 96
      feat_channels: 96
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
data:
  train:
    name: coco
    img_path: ../rmcv_yolo/images
    ann_path: ../rmcv_yolo/annotations/train.json
    input_size: [640,640] #[w,h]
    keep_ratio: True
    mixup: True
    load_mosaic: False
    pipeline:
      perspective: 0.0002
      scale: [0.5, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 5
      shear: 3
      translate: 0.1
      flip: 0.5
      hsv_h: 0.0138
      hsv_s: 0.464
      hsv_v: 0.464
  val:
    name: coco
    img_path: ../rmcv_yolo/images
    ann_path: ../rmcv_yolo/annotations/val.json
    input_size: [640,640] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
device:
  gpu_ids: [0]
  workers_per_gpu: 8
  batchsize_per_gpu: 32
schedule:
  resume:
#  load_model: nanodet_m.ckpt
  optimizer:
    name: SGD
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 300
    ratio: 0.01
  total_epochs: 100
  lr_schedule:
    name: MultiStepLR
    milestones: [30,60,90]
    gamma: 0.1
  val_intervals: 2
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 10

class_names: ['R1', 'B1', 'R2', 'B2', 'R3', 'B3', 'R4', 'B4','R5', 'B5', 'R7', 'B7', 'R10', 'B10', 'R11', 'B11', 'RE', 'BE']
